<a href="https://colab.research.google.com/github/mdayann/naive-bayes-intro/blob/main/NaiveBayesPerumahan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

In [119]:
dataset = pd.read_excel("perumahan.xlsx")
df = dataset.drop(columns="Aturan ke")

In [122]:
x = df.iloc[:, :3].values
y = df.iloc[:, -1].values

In [111]:
dataset

Aturan ke Harga Tanah Jarak dari pusat kota Ada angkutan umum  \
0          1       Murah                 Dekat             Tidak   
1          2      Sedang                 Dekat             Tidak   
2          3       Mahal                 Dekat             Tidak   
3          4       Mahal                  Jauh             Tidak   
4          5       Mahal                Sedang             Tidak   
5          6      Sedang                  Jauh               Ada   
6          7       Murah                  Jauh               Ada   
7          8       Murah                Sedang             Tidak   
8          9       Mahal                  Jauh               Ada   
9         10      Sedang                Sedang               Ada   

   Dipilih untuk perumahan  
0                        1  
1                        1  
2                        1  
3                        0  
4                        0  
5                        0  
6                        0  
7                        1  
8                        0  
9                        1

In [123]:
x

array([['Murah', 'Dekat', 'Tidak'],
       ['Sedang', 'Dekat', 'Tidak'],
       ['Mahal', 'Dekat', 'Tidak'],
       ['Mahal', 'Jauh', 'Tidak'],
       ['Mahal', 'Sedang', 'Tidak'],
       ['Sedang', 'Jauh', 'Ada'],
       ['Murah', 'Jauh', 'Ada'],
       ['Murah', 'Sedang', 'Tidak'],
       ['Mahal', 'Jauh', 'Ada'],
       ['Sedang', 'Sedang', 'Ada']], dtype=object)

In [124]:
print(x)

[['Murah' 'Dekat' 'Tidak']
 ['Sedang' 'Dekat' 'Tidak']
 ['Mahal' 'Dekat' 'Tidak']
 ['Mahal' 'Jauh' 'Tidak']
 ['Mahal' 'Sedang' 'Tidak']
 ['Sedang' 'Jauh' 'Ada']
 ['Murah' 'Jauh' 'Ada']
 ['Murah' 'Sedang' 'Tidak']
 ['Mahal' 'Jauh' 'Ada']
 ['Sedang' 'Sedang' 'Ada']]


In [125]:
print(y)

[1 1 1 0 0 0 0 1 0 1]


In [126]:
from sklearn.preprocessing import LabelEncoder

In [127]:
le = LabelEncoder()
x[:, 0] = le.fit_transform(x[:, 0])
x[:, 1] = le.fit_transform(x[:, 1])
x[:, 2] = le.fit_transform(x[:, 2])

In [128]:
print(x)

[[1 0 1]
 [2 0 1]
 [0 0 1]
 [0 1 1]
 [0 2 1]
 [2 1 0]
 [1 1 0]
 [1 2 1]
 [0 1 0]
 [2 2 0]]


**Split Data**

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [131]:
print(x_train)

[[0 2 1]
 [2 2 0]
 [2 0 1]
 [1 1 0]
 [1 2 1]
 [0 1 1]
 [1 0 1]
 [2 1 0]]


In [132]:
from sklearn.naive_bayes import GaussianNB

In [133]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [134]:
y_pred = classifier.predict(x_test)

In [137]:
print(y_pred)

[0 0]


In [138]:
print(y_test)

[1 0]


In [139]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [140]:
cm =confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [141]:
ac

0.5

In [150]:
x_pred = pd.read_excel("testing.xlsx")
testdf = x_pred.drop(columns="Aturan ke")
x = testdf.iloc[:, :].values
x

array([['Mahal', 'Jauh', 'Tidak'],
       ['Sedang', 'Dekat', 'Tidak'],
       ['Murah', 'Dekat', 'Ada'],
       ['Sedang', 'Sedang', 'Ada'],
       ['Murah', 'Sedang', 'Tidak']], dtype=object)

In [151]:
le = LabelEncoder()
x[:, 0] = le.fit_transform(x[:, 0])
x[:, 1] = le.fit_transform(x[:, 1])
x[:, 2] = le.fit_transform(x[:, 2])

In [152]:
x_pred["Dipilih"] = classifier.predict(x)
x_pred

Aturan ke Harga Tanah Jarak dari pusat kota Ada angkutan umum  Dipilih
0          1       Mahal                  Jauh             Tidak        0
1          2      Sedang                 Dekat             Tidak        1
2          3       Murah                 Dekat               Ada        1
3          4      Sedang                Sedang               Ada        1
4          5       Murah                Sedang             Tidak        1